import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "./_components/header/header";
import { Footer } from "./_components/footer/footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-center">
          <div>
            <div className="h-screen flex flex-col justify-between">
              <div>
                <Header />
                <main>{children}</main>
              </div>
              <Footer />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
